### ISSUE TITLE
[Bug Report] -bonds balance disappeared

### ISSUE THREAD

**Issue by fswshun** [keep3r-network/keep3r.governance#11]
The added amount disappeared.

It was displayed like this.
<img width="443" alt="スクリーンショット 2020-11-01 5 50 25" src="https://user-images.githubusercontent.com/73344798/97789748-389b1080-1c06-11eb-8490-75ee5df7a771.png">

But when it was time for activatable, it disappeared
![Elqw-oGXUAAEh0Y](https://user-images.githubusercontent.com/73344798/97789761-59636600-1c06-11eb-8446-86e6879b64e0.png)

If there are several similar reports on Twitter, please respond.

**Comment by Nutter79** [comment]
Looks like the issue has been resolved, but now when i try to remove the bonded KPR it doesn't allow me.
The balance of the bond is correct, but when i attempt to remove anything, nothing happens.
It seems like it still thinks i don't have any KPR to remove.

![image](https://user-images.githubusercontent.com/48455018/97798301-c4b83280-1c1c-11eb-887a-c6867aa11563.png)

When i click on remove, the balance shows zero (although when i click on the balance, it automatically enters the correct amount to remove).

![image](https://user-images.githubusercontent.com/48455018/97798308-e2859780-1c1c-11eb-8a5e-4d4c57b54eeb.png)

**Comment by Nutter79** [comment]
Looks like the issue has been resolved, but now when i try to remove the bonded KPR it doesn't allow me.
The balance of the bond is correct, but when i attempt to remove anything, nothing happens.
It seems like it still thinks i don't have any KPR to remove.

![image](https://user-images.githubusercontent.com/48455018/97798563-182b8000-1c1f-11eb-90aa-71d2502d0e45.png)


When i click on remove, the balance shows zero (although when i click on the balance, it automatically populates the correct amount to remove).

![image](https://user-images.githubusercontent.com/48455018/97798570-27123280-1c1f-11eb-8f6a-efe2be3d2467.png)

**Comment by fswshun** [comment]
I'm the same, pressing the remove button doesn't respond.

**Comment by kx9x** [comment]
> Looks like the issue has been resolved, but now when i try to remove the bonded KPR it doesn't allow me.
> The balance of the bond is correct, but when i attempt to remove anything, nothing happens.
> It seems like it still thinks i don't have any KPR to remove.
> 
> ![image](https://user-images.githubusercontent.com/48455018/97798563-182b8000-1c1f-11eb-90aa-71d2502d0e45.png)
> 
> When i click on remove, the balance shows zero (although when i click on the balance, it automatically populates the correct amount to remove).
> 
> ![image](https://user-images.githubusercontent.com/48455018/97798570-27123280-1c1f-11eb-8f6a-efe2be3d2467.png)

Did you unbond? After unbonding, it takes 14 days until you can withdraw. 

I'll have to check the code if there is an unbond button and if it isn't showing.

Here is the logic flow of K3PR entering and exiting:

Call bond() -> wait 3 days -> call activate -> either run jobs or call unbond() -> wait 14 days -> withdraw

**Comment by kx9x** [comment]
![image](https://user-images.githubusercontent.com/7820952/97807533-43f63800-1c16-11eb-936b-9dc5613b5b88.png)

It responds for me, but notice that the suggested autofill is my current balance (0.68) rather than my bonded balance (0.01936).

I bet the bug is related to that, since you cannot hit the button if the number in the amount field is greater than the suggested. I'll try fixing

**Comment by kx9x** [comment]
Fixed here:
![image](https://user-images.githubusercontent.com/7820952/97807661-eadad400-1c16-11eb-884b-fd0a671289bf.png)

https://github.com/keep3r-network/keep3r.governance/pull/12

**Comment by jsmellz** [comment]
Hmm, maybe we should add a remove/withdraw count down.

**Comment by fswshun** [comment]
I have activated and are currently bonded.
<img width="322" alt="スクリーンショット 2020-11-02 5 44 40" src="https://user-images.githubusercontent.com/73344798/97815022-a6127400-1cce-11eb-913f-a44527c063ea.png">

However, even if I enter the number that is bonding in the "amount the unbond" field, the remove button cannot be pressed.
<img width="323" alt="スクリーンショット 2020-11-02 5 44 31" src="https://user-images.githubusercontent.com/73344798/97815079-ef62c380-1cce-11eb-8e3a-b3cb173af2e9.png">
<img width="345" alt="スクリーンショット 2020-11-02 5 56 10" src="https://user-images.githubusercontent.com/73344798/97815267-2ab1c200-1cd0-11eb-911f-a79516d6cb0f.png">

Does this mean that I have to wait 14 days after activate to fill in the "amount the unbond" field? (Isn't it a bug?)

**Comment by kx9x** [comment]
@fswshun this is a bug and it is fixed by #12. Need someone to accept my code change and deploy the changes

**Comment by kx9x** [comment]
Since the issue being described in the latest comments in this thread is just #13, we should close this issue and move discussion there, since this thread's original issue is already resolved by #3
