### ISSUE TITLE
Unable to remove Bonded KPR

### ISSUE THREAD

**Issue by Nutter79** [keep3r-network/keep3r.governance#13]
The correct amount of tokens are showing under bonded section, but unable to remove any:
![image](https://user-images.githubusercontent.com/48455018/97806455-9c97f600-1c53-11eb-9fd1-5fda66e39bbf.png)

When i try to remove, nothing happens:
![image](https://user-images.githubusercontent.com/48455018/97806478-b0435c80-1c53-11eb-9ee1-17ea557d8c76.png)

**Comment by kx9x** [comment]
will be Resolved by #12

**Comment by Nutter79** [comment]
Seems to be resolved now, was able to remove the bonded KPR.
Would suggest some status information to show when the unbonding will be complete as once you unbond, your balance is showing as zero. 

Alittle unnerving waiting 14 days with a balance of zero and no info on whether the unbonding is being processed.
A countdown like when you join as a keeper would be good.

**Comment by kx9x** [comment]
A countdown would be good. 

Though I don't think Andre and Antonnell designed for so many speculators who were going to bond for no reason and then go straight into unbonding 😅

I was personally shocked to see people locking up almost $100,000 of collateral without knowing much about the process.

**Comment by kx9x** [comment]
If this issue is resolved, then it'd be good to close this thread as well. Thanks!

**Comment by Nutter79** [comment]
Thanks for the quick turn around guys.
