### ISSUE TITLE
withdraw error

### ISSUE THREAD

**Issue by fswshun** [keep3r-network/keep3r.governance#21]
<img width="316" alt="スクリーンショット 2020-11-17 10 56 11" src="https://user-images.githubusercontent.com/73344798/99333237-c6902000-28c3-11eb-836f-1b3187eb11be.png">
↑Even if I press "4.6901KP3R" on the upper right to do withdraw, it remains 0.

<img width="1076" alt="スクリーンショット 2020-11-17 10 56 55" src="https://user-images.githubusercontent.com/73344798/99334558-24bd0300-28c4-11eb-926f-961a42981c83.png">
↑Also, I can manually enter it in the field, but for some reason, even if I enter a number larger than my own (in the case of a photo, enter 5 instead of 4.69), metamask will start and you can apply.

By the way, I've tried withdraw by manually entering my own 4.69, but the metamask is pending. (This is a problem only for me, and there may be some people who succeeded in withdraw by manual input)

**Comment by JacobInCode** [comment]
Is this fixed?

**Comment by fswshun** [comment]
Probably not yet. It seems to be in progress now. The activity of my metamask remains pending for more than 24 hours. I also want to know how to deal with this.

**Comment by fswshun** [comment]
The problem is complete and I was able to withdraw safely. Thank you.
